name: terraform init
inputs:
  working-directory:
    required: true
  

runs:
  using: "composite"
  steps:
    - name: terraform init
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform init -upgrade=true -reconfigure -input=false -backend-config="resource_group_name=${{ var.TF_STATE_RG_NAME }}" -backend-config="storage_account_name=${{ var.TF_STATE_STORAGE_NAME }}" -backend-config="container_name=${{ var.TF_STATE_CONTAINER_NAME }}" -backend-config="key=${{ secrets.TFSTATE_KEY }}"
      shell: bash
