name: "🚀 dev-deployment"
run-name: '🚀 dev-deployment: "${{ github.ref_name }}"'

on:
  workflow_dispatch:

env:
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET}}
  ARM_CLIENT_ID: ${{ vars.AZURE_SERVICE_PRINCIPAL_ID}}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID}}

jobs:
  terraform-init:
    name: terraform init
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: terraform init
        working-directory: infrastructure
        run: |
          terraform init -upgrade=true -reconfigure -input=false -backend-config="resource_group_name=${{ vars.TF_STATE_RG_NAME }}" -backend-config="storage_account_name=${{ vars.TF_STATE_STORAGE_NAME }}" -backend-config="container_name=${{ vars.TF_STATE_CONTAINER_NAME }}" -backend-config="key=dev.tfstate"
        shell: bash