name: "🚀 dev-deployment"
run-name: '🚀 dev-deployment: "${{ github.ref_name }}"'

on:
  workflow_dispatch:

jobs:
  terraform-init:
    name: terraform init
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: terraform init
        uses: ./.github/actions/terraform-init
        with:
          secrets: inherit
          working-directory: infrastructure